# fly.toml app configuration file generated for dns302 on 2024-03-23T22:54:15+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dns302'
primary_region = 'ams'

[build]
  builder = 'heroku/buildpacks:20'
  buildpacks = ['https://cnb-shim.herokuapp.com/v1/hashnuke/elixir']

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
